name: Release

on:
  release:
    types: [released]
  schedule:
    - cron: '0 8 * * 2'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/service-build.yml
    with:
      checkout-type: latest-stable