name: Release

on:
  release:
    types: [released]
  schedule:
    - cron: '0 8 * * 2'

jobs:
  set-checkout-type:
    steps:
      - run: CHECKOUT_TYPE=latest-stable
  build:
    uses: ./.github/workflows/service-build.yml