on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      ##
      # Checkout branch (for push deployments)
      ##
      - name: Get branch name
        if: env.CHECKOUT_TYPE == 'branch'
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v3
        if: env.CHECKOUT_TYPE == 'branch'
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
      
      ##
      # Checkout latest stable release (for production releases)
      ##
      - name: Get latest stable release
        if: env.CHECKOUT_TYPE == 'latest-stable'
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl --silent --header "Accept: application/vnd.github.v3.sha" "{{env.GITHUB_API_URL}}/repos/{{env.GITHUB_REPOSITORY}}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"

      - name: Confirm release tag
        if: env.CHECKOUT_TYPE == 'latest-stable'
        run: |
          echo "Latest Stable Release Tag: cho ${{ steps.latestrelease.outputs.releasetag }}"
        
      - name: Checkout latest stable tag
        if: env.CHECKOUT_TYPE == 'latest-stable'
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latestrelease.outputs.releasetag }}

      ##
      # Echo the SHA
      ##
      - name: Echo the SHA
        run: git rev-parse --short HEAD