on:
  workflow_call:
    inputs:
      checkout-type:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      ##
      # Checkout branch (for push deployments)
      ##
      - name: Get branch name
        if: inputs.checkout-type == 'branch'
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v3
        if: inputs.checkout-type  == 'branch'
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
      
      ##
      # Checkout latest stable release (for production releases)
      ##
      - name: Get latest stable release
        if: inputs.checkout-type  == 'latest-stable'
        id: latest-stable-version
        run: |
          echo "LATEST_STABLE_VERSION=$(curl --silent --header "Accept: application/vnd.github.v3.sha" "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')" >> $GITHUB_OUTPUT

      - name: Confirm release tag
        if: inputs.checkout-type  == 'latest-stable'
        run: |
          echo "Latest Stable Release Tag: ${{ steps.latest-stable-version.outputs.LATEST_STABLE_VERSION }}"
        
      - name: Checkout latest stable tag
        if: inputs.checkout-type  == 'latest-stable'
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.latest-stable-version.outputs.LATEST_STABLE_VERSION }}

      ##
      # Echo the SHA
      ##
      - name: Echo the SHA
        run: git rev-parse --short HEAD
      
      - name: Echo the content of test
        run: cat test.txt